### ISSUE TITLE
nsupers exceeds the 

### ISSUE THREAD

**Issue by nilsnevertree** [nilsnevertree/CLEO-sdm-eurec4a#25]
````
terminate called after throwing an instance of 'std::invalid_argument'
  what():  UNDEFINED BEHAVIOUR: Number of super-droplets in the domain cannot become larger than the size of the super-droplets' view
Traceback (most recent call last):
  File "/home/m/m301096/CLEO/examples/eurec4a1d/scripts/eurec4a1d_stationary.py", line 377, in <module>
    consts = pysetuptxt.get_consts(setupfile, isprint=False)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/m/m301096/CLEO/pySD/sdmout_src/pysetuptxt.py", line 28, in get_consts
    return consts_dict(setuptxt, isprint=isprint)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/m/m301096/CLEO/pySD/sdmout_src/pysetuptxt.py", line 38, in consts_dict
    consts.update(cxx2py.derive_more_floats(consts))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/m/m301096/CLEO/pySD/cxx2py.py", line 113, in derive_more_floats
    "COORD0"     : consts["TIME0"]*consts["W0"], # characteristic coordinate grid scale [m]
                   ~~~~~~^^^^^^^^^
KeyError: 'TIME0'
````
This error is thrown, whenever the maximum number of superdroplets is lower than the initialized number of superdroplets.

**Comment by nilsnevertree** [comment]
Closed by setting proper values in the setup file
