### ISSUE TITLE
Problem with zarr

### ISSUE THREAD

**Issue by nilsnevertree** [nilsnevertree/CLEO-sdm-eurec4a#4]
````python

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/m/m301096/CLEO/examples/rainshaft1d/rainshaft1d.py", line 190, in <module>
    time = pyzarr.get_time(dataset)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/m/m301096/CLEO/pySD/sdmout_src/pyzarr.py", line 83, in get_time
    return timedata.Time(dataset)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/m/m301096/CLEO/pySD/sdmout_src/timedata.py", line 29, in __init__
    timeds = self.tryopen_time(dataset) # time from dataset
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/m/m301096/CLEO/pySD/sdmout_src/timedata.py", line 43, in tryopen_time
    timeds = xr.open_dataset(dataset, engine="zarr",
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/work/mh1126/m300950/condaenvs/superdropsenv/lib/python3.11/site-packages/xarray/core/dataset.py", line 1473, in __getitem__
    return self._construct_dataarray(key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/work/mh1126/m300950/condaenvs/superdropsenv/lib/python3.11/site-packages/xarray/core/dataset.py", line 1384, in _construct_dataarray
    _, name, variable = _get_virtual_variable(self._variables, name, self.dims)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/work/mh1126/m300950/condaenvs/superdropsenv/lib/python3.11/site-packages/xarray/core/dataset.py", line 196, in _get_virtual_variable
    raise KeyError(key)
KeyError: 'time'

````

this occured in 131dc0a835a9eac08dfbe9b461421c448eed3b5b from ``rainshaft1D-eurec4a-droplet-distributions``

**Comment by nilsnevertree** [comment]
removed ``./build`` but same problem occured.

**Comment by nilsnevertree** [comment]
This issue arises actually beforehand.

````log
[100%] Built target rshaft1D
terminate called after throwing an instance of 'std::invalid_argument'
  what():  number of gridboxes read from gridfile not consistent with ngbxs

---- config from  /home/m/m301096/CLEO/build//bin/rain1d_setup.txt -----
````
Thus it is due to an empty zarr file, because the model didn't finish properly.

To resolve this, make sure, that 
- number of gridboxes is consitent in config.txt and the python script.

````txt
### SDM Runtime parameters ###
# domain setup #
nspacedims = 1                            # no. of spatial dimensions to model
ngbxs = 60                               # total number of Gbxs
totnsupers = 15360                        # (initial) total no. of SDs
````

````python

### --- settings for 1-D gridbox boundaries --- ###
zgrid       = [0, 1200, 20]      # evenly spaced zhalf coords [zmin, zmax, zdelta] [m]
xgrid       = np.array([0, 20])  # array of xhalf coords [m]
ygrid       = np.array([0, 20])  # array of yhalf coords [m]

### --- settings for initial superdroplets --- ###
# initial superdroplet coordinates
zlim        = 800       # min z coord of superdroplets [m]
npergbx     = 256       # number of superdroplets per gridbox
````

**Comment by nilsnevertree** [comment]
This is not the complete solution!

In the config.txt the 
``totnsupers = N                        # (initial) total no. of SDs``

Needs to be 
````python
zgrid       = [0, 1200, 20]      # evenly spaced zhalf coords [zmin, zmax, zdelta] [m]

# ...

### --- settings for initial superdroplets --- ###
# initial superdroplet coordinates
zlim        = 800       # min z coord of superdroplets [m]
npergbx     = 256       # number of superdroplets per gridbox

totnsupers  = npergbx  * (zgrid[1] - zlim) / zgrid[2]
````

So this meansm the total number of SD is the ones which are initialzed in the upper gridboxes, if the setup with 
````python 
nsupers = crdgens.nsupers_at_domain_top(gridfile, constsfile, npergbx, zlim)
````
